# Generated by Django 4.0.2 on 2022-02-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_arcticle_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='arcticle',
            new_name='article',
        ),
    ]
